name: sliver_stream_builder
description: Package to transform data stream to sliver list or sliver grid
version: 0.3.1
repository: https://github.com/massa-org/sliver_stream_builder

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  fast_i18n: ^5.10.0

  flutter_lints: ^2.0.1